# Generated by Django 3.1.7 on 2021-03-28 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(default='', verbose_name='Содержание')),
                ('state', models.IntegerField(choices=[(0, 'Отложено'), (1, 'Активно'), (2, 'Выполнено')], default='0')),
                ('importance', models.BooleanField(default=False, verbose_name='Важность')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
