# Generated by Django 3.1.7 on 2021-03-28 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='importance',
            field=models.BooleanField(default=False, verbose_name='Важно'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 21, 50, 53, 597108), verbose_name='Дата'),
        ),
    ]
